FacultyAA:
  role: faculty
  campus: UMAA
RegularStaffAA:
  role: staff
  campus: UMAA
EnrolledStudentStudentAA:
  role: student
  campus: UMAA
StudentAA:
  role: student
  campus: UMAA
SponsoredAffiliateAA:
  role: student
  campus: UMAA
FacultyFLNT:
  role: faculty
  campus: UMFL
RegularStaffFLNT:
  role: student
  campus: UMFL
  EnrolledStudentFLNT:
  role: student
  campus: UMFL
StudentFLNT:
  role: student
  campus: UMFL
FacultyDBRN:
  role: student
  campus: UMDB
RegularStaffDBRN:
  role: student
  campus: UMDB
EnrolledStudentDBRN:
  role: student
  campus: UMDB
TemporaryStaffAA:
  role: student
  campus: UMAA
Retiree:
  role: student
  campus: UMAA
