- key: FacultyAA
  role: faculty
  campus: UMAA
- key: RegularStaffAA
  role: staff
  campus: UMAA
- key: EnrolledStudentStudentAA
  role: student
  campus: UMAA
- key: StudentAA
  role: student
  campus: UMAA
- key: SponsoredAffiliateAA
  role: sponsored_affiliate
  campus: UMAA
- key: FacultyFLNT
  role: faculty
  campus: UMFL
- key: RegularStaffFLNT
  role: student
  campus: UMFL
- key: EnrolledStudentFLNT
  role: student
  campus: UMFL
- key: StudentFLNT
  role: student
  campus: UMFL
- key: FacultyDBRN
  role: faculty
  campus: UMDB
- key: RegularStaffDBRN
  role: staff
  campus: UMDB
- key: EnrolledStudentDBRN
  role: student
  campus: UMDB
- key: TemporaryStaffAA
  role: temporary_staff 
  campus: UMAA
- key: Retiree
  role: retiree
